# .travis.yml
language: node_js
node_js:
  - '8'
branches:
  only:
    - source
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - CURRENT_BRANCH=source USE_SSH=true
  - cd website && npm install && GIT_USER="${GH_NAME}" npm run publish-gh-pages
